# Generated by Django 4.2.18 on 2025-01-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_quote', to='tickets.quote'),
        ),
    ]
