# Generated by Django 4.2.18 on 2025-01-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_quote_alter_ticket_subject_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject_purchase',
            field=models.CharField(max_length=200),
        ),
    ]
