# Generated by Django 4.2.18 on 2025-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_quote_ticket_alter_ticket_subject_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
