# Generated by Django 4.2.18 on 2025-01-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_quote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotesaaa', to='tickets.ticket'),
        ),
    ]
