# Generated by Django 4.2.18 on 2025-01-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_quote_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': 'Cotações'},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='description_quotes',
        ),
    ]
