# Generated by Django 4.2.18 on 2025-01-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_rename_description_quotes_quote_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='description_quotes',
        ),
    ]
