# Generated by Django 4.2.18 on 2025-01-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_description_quote_description_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='value',
            field=models.FloatField(),
        ),
    ]
