# Generated by Django 4.2.18 on 2025-01-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_quote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description_quotes',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.IntegerField(default=0, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.CharField(max_length=100, verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name_user',
            field=models.CharField(max_length=100, verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject_purchase',
            field=models.CharField(max_length=200, verbose_name='Assunto da Compra'),
        ),
    ]
