# Generated by Django 4.2.18 on 2025-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_quote_description_quotes_alter_quote_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_ticket',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
