# Generated by Django 4.2.18 on 2025-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_status_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status_ticket',
            field=models.IntegerField(default=1),
        ),
    ]
