# Generated by Django 4.2.18 on 2025-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_status_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reason_for_rejection',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
