# Generated by Django 4.2.17 on 2025-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_reason_for_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='who_approved',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gestor que aprovou'),
        ),
    ]
