# Generated by Django 4.2.17 on 2025-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_who_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovado'),
        ),
    ]
